"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ['main.py']
APP_NAME = "Super Mario Bros PC"

files = ["saveData.json","settings.json",
    ("sprites",glob.glob("sprites/*.json")),
    ("textures",glob.glob("textures/*.png")),
    ("sfx",glob.glob("sfx/*.wav")+glob.glob("sfx/*.mp3")),
    ("img",glob.glob("img/*.png")+glob.glob("img/*.gif")),]

for name in glob.glob("levels/*[1-8]"):
    level = name[len(name)-1:]
    files.append(("levels/"+level,glob.glob(name+"/*.json")))
    files.append(("levels/"+level+"/level1",glob.glob(name+"/level1/*.csv")))
    files.append(("levels/"+level+"/level2",glob.glob(name+"/level2/*.csv")))
    files.append(("levels/"+level+"/level3",glob.glob(name+"/level3/*.csv")))
    files.append(("levels/"+level+"/level4",glob.glob(name+"/level4/*.csv")))

OPTIONS = {
    "iconfile": "App_Icon.icns",
    "excludes": ["zmq"],
    "plist": {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleGetInfoString": "This is a copy of the NES Super Mario Bros I created myself.\n I made this to practice coding with python.",
        "NSHumanReadableCopyright": "All rights go to Nintendo. This is a fan made version. This app is not for profit."}}

setup(
    name=APP_NAME,
    app=APP,
    data_files=files,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
